CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  username TEXT,
  name TEXT,
  role TEXT,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  ticket_code TEXT,
  title TEXT,
  description TEXT,
  category TEXT,
  status TEXT,
  priority TEXT,
  url_foto TEXT,
  created_by UUID REFERENCES profiles(id),
  assigned_to UUID REFERENCES profiles(id),
  updated_at TIMESTAMPTZ,
  received_by_admin_at TIMESTAMPTZ,
  forwarded_to_helpdesk_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

CREATE TABLE ticket_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  actor_id UUID,
  actor_name TEXT,
  actor_role TEXT,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ticket_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id),
  message TEXT
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  recipient_id UUID REFERENCES profiles(id),
  title TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  recipient_role TEXT
);